###
POST http://localhost:8001/api/product?version=v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjY3MDdhMzJlOGVjNTI3NDAzMWJkM2RhIiwiZXhwaXJlc0F0IjoiMjAyNC0wOC0wOFQyMDowNTowMi42MTRaIiwiaWF0IjoxNzIzMTQzOTAyfQ.n1EGisnI3hkHmeQaSQ1HQecEhSJnPi4D7nMC8ViTrBc

{
  "name": "Sample Product 2",
  "description": "This is a sample product description.",
  "price": 99.99,
  "stock": 100,
  "category": "Electronics",
  "imageUrl": "https://example.com/sample-product.jpg",
  "status": "Available",
  "createdAt": "2024-08-08T12:00:00Z",
  "updatedAt": ""
}

# {
#   "message": "Product created successfully",
#   "product": {
#     "productId": "7b548009-efe3-40bf-ad1c-1fdbbfa76ea2",
#     "name": "Sample Product 2",
#     "description": "This is a sample product description.",
#     "price": 99.99,
#     "stock": 100,
#     "category": "Electronics",
#     "imageUrl": "https://example.com/sample-product.jpg",
#     "createdAt": "2024-08-08T12:00:00.000Z",
#     "updatedAt": null,
#     "_id": "66b51b47236ede501c38fa33",
#     "__v": 0
#   }
# }

###

GET http://localhost:8001/api/product?version=v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjY3MDdhMzJlOGVjNTI3NDAzMWJkM2RhIiwiZXhwaXJlc0F0IjoiMjAyNC0wOC0wOFQyMDowNTowMi42MTRaIiwiaWF0IjoxNzIzMTQzOTAyfQ.n1EGisnI3hkHmeQaSQ1HQecEhSJnPi4D7nMC8ViTrBc

{
 
}

###
GET http://localhost:8001/api/product/7b548009-efe3-40bf-ad1c-1fdbbfa76ea2?version=v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjY3MDdhMzJlOGVjNTI3NDAzMWJkM2RhIiwiZXhwaXJlc0F0IjoiMjAyNC0wOC0wOFQyMDowNTowMi42MTRaIiwiaWF0IjoxNzIzMTQzOTAyfQ.n1EGisnI3hkHmeQaSQ1HQecEhSJnPi4D7nMC8ViTrBc

{
 
}


###
PUT http://localhost:8001/api/product/7b548009-efe3-40bf-ad1c-1fdbbfa76ea2?version=v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNjY3MDdhMzJlOGVjNTI3NDAzMWJkM2RhIiwiZXhwaXJlc0F0IjoiMjAyNC0wOC0wOFQyMDowNTowMi42MTRaIiwiaWF0IjoxNzIzMTQzOTAyfQ.n1EGisnI3hkHmeQaSQ1HQecEhSJnPi4D7nMC8ViTrBc

{
  "name": "Ear Pods",
  "description": "This is a sample product description.",
  "price": 99.99,
  "stock": 100,
  "category": "Electronics",
  "imageUrl": "https://example.com/sample-product.jpg",
  "status": "Available",
  "createdAt": "2024-08-08T12:00:00Z",
  "updatedAt": "2024-09-08T12:00:00Z"
}
